layout_spectrum: 0.9456125998403877
typography_spectrum: 0.41971585573628545
color:
  saturation: 0.3995121349580586
  brandStrength: 0.599942401284352
  lightness: 0.8499372971709818
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
  rhythmicContrast: 0.3200724159833044
author:
  name: Steven Donaldson
  email: info@stevendonaldson.co.uk
  url: www.stevendonaldson.co.uk
name: FeardOfTheBeard
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Photography, Technology, Writing'
description: All the things that interest me
