collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0
  lightness: 1
  brandColors:
    - '#242F45'
    - '#869DBC'
    - '#733B54'
    - '#DC6955'
    - '#FFC062'
  rhythmicContrast: 0
typography_spectrum: 0.5025063
layout_spectrum: 1
name: StevenDonaldsonPhotography
